### ISSUE TITLE
Pod::Weaver leaves a blank line that irritates Test::TidyAll.

### ISSUE THREAD

**Issue by hartzell** [rjbs/Pod-Weaver#35]
I recently added Test::TidyAll to my Dist::Zilla bundle and discovered that it's complaining about the files created by a `dzil build`.  It seems that e.g. when the pod for a function section is lifted out and placed elsewhere, a blank line is left behind, e.g. 

```
  ...;
}

=func something

yada yada

=cut

sub something {...}
```

becomes

```
  ...;
}


sub something {...}
```

and tidyall wants to tidy up that extra blank line.

A quick perusal couldn't find where the input doc is being manipulated.  I suspect it's a ppi thing, and perhaps the collector (I think that's the guilty party) could also consume that extra newline?

A pointer to places to dig and check would send me off looking for a patch to propose.

Thanks!

**Comment by rjbs** [comment]
It's probably something you'd have to do in PerlMunger or Pod::Elemental.

I think this is going to end up being a big pain, but I'm not sure.

**Comment by hartzell** [comment]
I'm doing much less Perl stuff at work these days and have punted on Test::TidyAll.  I doubt I'll have a chance to pursue this.

Thanks for the followup.

**Comment by hartzell** [comment]
Having been bought onto another Perl project I rediscovered my frustration with this problem and rediscovered this issue.

I've figured out that adding `-blbs=2` to my `perltidy` args allows `Dist::Zilla::Plugin::Test::TidyAll` to function reasonably.

Here's the configuration from my `tidyall.rc`

```
; the -nomem works around a perltidy issue that leaves spurious LOG files.
; -nbbc avoids spats between tidyall and dzil
; -blbs=2 avoids spats with extra blank line where pod used to be
argv = -pbp -nse -nst -ci=2 -nomem -nbbc -blbs=2
```

**Comment by hartzell** [comment]
Spoke too soon.  This seems to work:

```
; the -nomem works around a perltidy issue that leaves spurious LOG files.
; -nbbc avoids spats between tidyall and dzil
; -blbs=2 avoids spats with extra blank line where pod used to be
argv = -pbp -nse -nst -ci=2 -nomem -nbbc -blbs=2 -mbl=3
```
